apiV1Prefix: /api/v1/auth

spring:
  application:
    name: AUTH
  datasource: # db config seems not to be used
    url: jdbc:mysql://localhost:3306/authentication?serverTimezone=Africa/Douala
    username: root
    password: prodev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9008
  servlet:
    context-path: /

#openapi:
#  service:
#    title: auth ms doc
#    version: 1.0.0
#    url: http://localhost:8222 #api gateway url
#
#springdoc:
#  api-docs:
#    path: /auth/v3/api-docs
#  swagger-ui:
#    path: /auth/swagger-ui.html

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # where to register this client
#    healthcheck: this causes an error check later
    lease:
      duration: 5
    enabled: false  # false value disables discovery request.

externals:
  base-url:
    file-management: http://localhost:8084/api/v1/files
    nofia: http://localhost:8082/api/v1/nofia

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      token:
        expiration: 86400000  # 86400000 = 1 day
      refresh-token:
        expiration: 604800000 # 604800000 = 7 days

#logging:
#  level:
#    com.example.howtodoinjava: DEBUG